spring.application.name=product-service

# keep your service on 8084
server.port=8084

# ✅ Use Docker creds (root/root), auth DB = admin
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/product_db?authSource=admin
